CREATE TABLE `notificationBroadcasts` (
	`id` varchar(64) NOT NULL,
	`name` varchar(255) NOT NULL,
	`titleEn` varchar(255) NOT NULL,
	`titleAr` varchar(255),
	`messageEn` text NOT NULL,
	`messageAr` text,
	`targetAudience` enum('all_users','customers_with_orders','customers_without_orders','specific_users') NOT NULL,
	`targetUserIds` text,
	`channels` text,
	`scheduledFor` timestamp,
	`status` enum('draft','scheduled','sending','sent','failed') DEFAULT 'draft',
	`totalRecipients` int DEFAULT 0,
	`sentCount` int DEFAULT 0,
	`deliveredCount` int DEFAULT 0,
	`failedCount` int DEFAULT 0,
	`createdBy` varchar(64) NOT NULL,
	`createdAt` timestamp DEFAULT (now()),
	`sentAt` timestamp,
	CONSTRAINT `notificationBroadcasts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `notificationPreferences` (
	`id` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`orderStatusInApp` boolean DEFAULT true,
	`orderStatusEmail` boolean DEFAULT true,
	`orderStatusSms` boolean DEFAULT false,
	`orderStatusPush` boolean DEFAULT true,
	`announcementsInApp` boolean DEFAULT true,
	`announcementsEmail` boolean DEFAULT true,
	`announcementsSms` boolean DEFAULT false,
	`announcementsPush` boolean DEFAULT false,
	`promotionsInApp` boolean DEFAULT true,
	`promotionsEmail` boolean DEFAULT true,
	`promotionsSms` boolean DEFAULT false,
	`promotionsPush` boolean DEFAULT false,
	`remindersInApp` boolean DEFAULT true,
	`remindersEmail` boolean DEFAULT false,
	`remindersSms` boolean DEFAULT false,
	`remindersPush` boolean DEFAULT true,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `notificationPreferences_id` PRIMARY KEY(`id`),
	CONSTRAINT `notificationPreferences_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `notificationTemplates` (
	`id` varchar(64) NOT NULL,
	`name` varchar(255) NOT NULL,
	`type` enum('order_status','admin_announcement','system_alert','customer_message','promotion','reminder') NOT NULL,
	`titleEn` varchar(255) NOT NULL,
	`titleAr` varchar(255),
	`messageEn` text NOT NULL,
	`messageAr` text,
	`variables` text,
	`isActive` boolean DEFAULT true,
	`createdBy` varchar(64),
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `notificationTemplates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `notifications` (
	`id` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`type` enum('order_status','admin_announcement','system_alert','customer_message','promotion','reminder') NOT NULL,
	`channel` enum('in_app','email','sms','push') NOT NULL,
	`title` varchar(255) NOT NULL,
	`titleAr` varchar(255),
	`message` text NOT NULL,
	`messageAr` text,
	`actionUrl` varchar(512),
	`metadata` text,
	`isRead` boolean DEFAULT false,
	`isArchived` boolean DEFAULT false,
	`deliveryStatus` enum('pending','sent','delivered','failed','bounced') DEFAULT 'pending',
	`deliveredAt` timestamp,
	`readAt` timestamp,
	`scheduledFor` timestamp,
	`expiresAt` timestamp,
	`priority` enum('low','medium','high','urgent') DEFAULT 'medium',
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `notifications_id` PRIMARY KEY(`id`)
);
