CREATE TABLE `media_library` (
	`id` varchar(64) NOT NULL,
	`file_name` varchar(255) NOT NULL,
	`file_type` varchar(20) NOT NULL,
	`mime_type` varchar(100) NOT NULL,
	`file_size` varchar(50),
	`url` varchar(1024) NOT NULL,
	`thumbnail_url` varchar(1024),
	`width` int,
	`height` int,
	`duration` int,
	`category` varchar(100),
	`tags` json,
	`used_in` json,
	`is_active` boolean DEFAULT true,
	`uploaded_by` varchar(64),
	`uploaded_at` timestamp DEFAULT (now()),
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `media_library_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `website_settings` (
	`id` varchar(64) NOT NULL,
	`hero_title_en` text,
	`hero_title_ar` text,
	`hero_subtitle_en` text,
	`hero_subtitle_ar` text,
	`hero_description_en` text,
	`hero_description_ar` text,
	`background_videos` json,
	`background_images` json,
	`slideshow_speed` int DEFAULT 5000,
	`about_title_en` text,
	`about_title_ar` text,
	`about_description_en` text,
	`about_description_ar` text,
	`feature1_title_en` text,
	`feature1_title_ar` text,
	`feature1_desc_en` text,
	`feature1_desc_ar` text,
	`feature2_title_en` text,
	`feature2_title_ar` text,
	`feature2_desc_en` text,
	`feature2_desc_ar` text,
	`feature3_title_en` text,
	`feature3_title_ar` text,
	`feature3_desc_en` text,
	`feature3_desc_ar` text,
	`contact_email` varchar(255),
	`contact_phone` varchar(50),
	`contact_whatsapp` varchar(50),
	`contact_address` text,
	`instagram_url` varchar(512),
	`facebook_url` varchar(512),
	`tiktok_url` varchar(512),
	`meta_title_en` varchar(255),
	`meta_title_ar` varchar(255),
	`meta_description_en` text,
	`meta_description_ar` text,
	`meta_keywords` text,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `website_settings_id` PRIMARY KEY(`id`)
);
